language: node_js
node_js:
   - 6.9
 
branches:
   only:
      - master

before_script:
   - npm install -g firebase-tools

script:
   - npm run start

after_success:
   - firebase deploy --token $FIREBASE_TOKEN