language: node_js
node_js:
   - 8.5.0
 
branches:
   only:
      - master

before_script:
   - npm install -g firebase-tools

script:
   - npm run deploy

after_success:
   - firebase deploy --token $FIREBASE_TOKEN